import { StoreSettings, Category, Product, Banner, Coupon, FAQ, Review } from '../types';

export const initialSettings: StoreSettings = {
  storeNameBn: 'পিওর ঘর (PureGhor)',
  storeNameEn: 'PureGhor Organic Store',
  taglineBn: 'সিলেটের বিখ্যাত ব্র্যান্ড — ১০০% খাঁটি ও অর্গানিক পণ্যের বিশ্বস্ত ঠিকানা',
  taglineEn: '100% Pure, Organic & Natural Food Store',
  logoUrl: '/logo.svg',
  faviconUrl: '/favicon.svg',
  phone: '01754-991822',
  whatsapp: '01754-991822',
  email: 'pureghornatural@gmail.com',
  addressBn: 'লালাবাজার, দক্ষিণ সুরমা, সিলেট। আল বুরাক শপিং সিটি, বিশ্বনাথ',
  addressEn: 'Lalabazar, Dakshin Surma, Sylhet. Al Burak Shopping City, Bishwanath',
  businessHours: 'প্রতিদিন সকাল ৯টা থেকে রাত ১০টা পর্যন্ত',
  isCodAvailable: true,
  deliveryCharges: {
    insideDhaka: 80,
    outsideDhaka: 130,
    insideSylhet: 50,
    outsideSylhet: 120,
  },
  freeDeliveryThreshold: 2000,
  socialLinks: {
    facebook: 'https://www.facebook.com/share/v/194qYMqpDL/',
    instagram: 'https://instagram.com/pureghor',
    youtube: 'https://youtube.com/pureghor',
    whatsapp: 'https://wa.me/8801754991822',
  },
  currency: 'BDT',
  currencySymbol: '৳',
  taxText: 'সকল মূল্যে ভ্যাট অন্তর্ভুক্ত',
  themeColors: {
    primaryGreen: '#5EB809',
    deepGreen: '#004F18',
    warmCream: '#F5FBF2',
    honeyAmber: '#E89D10',
    terracotta: '#B85C38',
    neutralText: '#102B16',
    border: '#DCECD5',
  },
  announcementBar: {
    enabled: true,
    textBn: '🚚 সারা বাংলাদেশে ক্যাশ অন ডেলিভারি | বিশ্বনাথ শাখা উদ্বোধন উপলক্ষে বিশেষ ১০% ডিসকাউন্ট!',
    linkUrl: '/shop',
  },
  trustStrip: [
    {
      id: 'ts-1',
      icon: 'ShieldCheck',
      titleBn: 'খাঁটি উৎস থেকে সংগ্রহ',
      descBn: 'সরাসরি কৃষক ও প্রাকৃতিক উৎস থেকে শতভাগ পরীক্ষিত মান',
    },
    {
      id: 'ts-2',
      icon: 'PackageCheck',
      titleBn: 'নিরাপদ ফুড-গ্রেড প্যাকেজিং',
      descBn: 'স্বাস্থ্যসম্মত ও বায়ুরোধী প্রটেক্টিভ জার ও প্যাকেট',
    },
    {
      id: 'ts-3',
      icon: 'Truck',
      titleBn: 'ক্যাশ অন ডেলিভারি',
      descBn: 'পণ্য হাতে পেয়ে চেক করে মূল্য পরিশোধ করুন',
    },
    {
      id: 'ts-4',
      icon: 'Headphones',
      titleBn: 'হোয়াটসঅ্যাপ ও সরাসরি সাপোর্ট',
      descBn: 'যেকোনো প্রয়োজনে সরাসরি কল বা হোয়াটসঅ্যাপে কথা বলুন',
    },
  ],
  aboutUsContent: {
    headline: 'আমাদের পথচলা ও খাঁটি পণ্যের অঙ্গীকার',
    storyBn: 'PureGhor প্রতিষ্ঠিত হয়েছে খাঁটি, ভেজালমুক্ত ও প্রাকৃতিক খাদ্যাভ্যাস সবার ঘরে ঘরে পৌঁছে দেওয়ার লক্ষ্যে। আমাদের যাত্রা শুরু সিলেটের পুণ্যভূমি লালাবাজার ও বিশ্বনাথ থেকে। মধ্যস্বত্বভোগী বা কেমিক্যালের কৃত্রিমতা ছাড়া প্রকৃতির সেরা উপহারটি আপনার পরিবারের কাছে পৌঁছে দেওয়াই আমাদের লক্ষ্য।',
    sourcingBn: 'সুন্দরবনের গভীর অরণ্যের মৌয়ালদের থেকে খাঁটি মধু, যশোরের ঐতিহ্যবাহী গাছিদের খাঁটি খেজুরের গুড়, সিরাজগঞ্জের গাভীর দুধের মাখনের দানাদার গাওয়া ঘি, মানিকগঞ্জের কাঠের ঘানির প্রথম চাপের সরিষার তেল এবং আন্তর্জাতিক গ্রেডের অর্গানিক ওটস ও সুপারফুড সংগ্রহ করি।',
    promiseBn: 'আমরা ল্যাব টেস্ট ও কঠোর মান নিয়ন্ত্রণের মাধ্যমে প্রতিটি পণ্য বাজারজাত করি। আপনাদের আস্থা ও সুস্থতাই আমাদের পথচলার শক্তি।',
  },
  isSetupComplete: true,
  updatedAt: new Date().toISOString(),
};

export const initialCategories: Category[] = [
  {
    id: 'cat-honey',
    nameBn: 'মধু ও হানি নাট',
    nameEn: 'Honey & Honey Nut',
    slug: 'honey-nuts',
    descriptionBn: 'কালোজিরা ফুলের মধু, সুন্দরবনের খলিশা মধু ও কাজু-পেস্তায় ভরপুর প্রিমিয়াম হানি নাট।',
    imageUrl: '/images/uploaded/img3.jpg',
    displayOrder: 1,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-nuts-seeds',
    nameBn: 'ড্রাই ফ্রুটস ও বাদাম',
    nameEn: 'Nuts, Seeds & Dry Fruits',
    slug: 'nuts-and-seeds',
    descriptionBn: '৪ জার স্পেশাল কম্বো, কাঠবাদাম, কাজুবাদাম, গোল্ডেন কিসমিস, কুমড়ো বীজ ও প্রিমিয়াম আখরোট।',
    imageUrl: '/images/uploaded/img7.jpg',
    displayOrder: 2,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-ghee-oil',
    nameBn: 'ঘি ও খাঁটি তেল',
    nameEn: 'Ghee & Pure Oils',
    slug: 'ghee-and-oils',
    descriptionBn: 'সিরাজগঞ্জের দানাদার গাওয়া ঘি, কাঠের ঘানির সরিষার তেল, স্প্যানিশ অলিভ অয়েল ও খাঁটি কালোজিরা তেল।',
    imageUrl: '/images/uploaded/img6.jpg',
    displayOrder: 3,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-oats',
    nameBn: 'ওটস ও সুপারফুড',
    nameEn: 'Oats & Superfoods',
    slug: 'oats-and-superfood',
    descriptionBn: 'কোয়েকার ওটস, অস্ট্রেলিয়ান বেবি ওটস, অর্গানিক রোল্ড ওটস, চিয়া সিড এবং ক্রিস্পি ওট চকো বার।',
    imageUrl: '/images/uploaded/img5.jpg',
    displayOrder: 4,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-gur',
    nameBn: 'খেজুরের গুড় ও মিষ্টি',
    nameEn: 'Date Palm Jaggery',
    slug: 'khejurer-gur',
    descriptionBn: 'যশোরের বিখ্যাত খাঁটি ঝোলা গুড়, নলেন পাটালি ও প্রাকৃতিক মিষ্টি খাবার।',
    imageUrl: '/images/pureghor/772513850_1055475870270979_5142302322816849426_n.jpeg',
    displayOrder: 5,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-spices-special',
    nameBn: 'বালাচাও ও মসলা',
    nameEn: 'Spices & Balachao',
    slug: 'spices-and-balachao',
    descriptionBn: 'স্পেশাল হোমমেড ক্রিস্পি চিংড়ি বালাচাও, অর্গানিক চিয়া সিড ও পাহাড়ি চা।',
    imageUrl: '/images/uploaded/img9.jpg',
    displayOrder: 6,
    isActive: true,
    type: 'food',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-honey-kalijira',
    nameBn: 'খাঁটি কালোজিরা ফুলের মধু (PureGhor Special)',
    nameEn: 'Pure Kalijira Flower Honey',
    slug: 'pure-kalijira-flower-honey',
    sku: 'PG-HNY-KALIJIRA',
    categoryId: 'cat-honey',
    shortDescriptionBn: 'কালোজিরা ফুল ফোটার মৌসুমে সরাসরি মৌবাক্স থেকে সংগৃহীত শতভাগ খাঁটি ও ঔষধি গুণসম্পন্ন মধু।',
    descriptionBn: 'কালোজিরা ফুলের মধু প্রাকৃতিক রোগ প্রতিরোধ ক্ষমতার এক মহৌষধ। এর গাঢ় রঙ ও অতুলনীয় সুমিষ্ট গন্ধ শরীরকে চাঙ্গা রাখতে সাহায্য করে। কোনো প্রকার হিটিং বা কৃত্রিম চিনি ছাড়াই কাচের বয়ামে বাজারজাত করা হয়।',
    price: 1100,
    salePrice: 950,
    currency: 'BDT',
    stock: 50,
    lowStockThreshold: 10,
    weight: 500,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 600, salePrice: 520, stock: 30, sku: 'PG-HNY-KJ-250' },
      { weight: 500, unit: 'gm', price: 1100, salePrice: 950, stock: 50, sku: 'PG-HNY-KJ-500' },
      { weight: 1, unit: 'kg', price: 2100, salePrice: 1850, stock: 20, sku: 'PG-HNY-KJ-1KG' },
    ],
    images: [
      {
        url: '/images/uploaded/img3.jpg',
        alt: 'খাঁটি কালোজিরা ফুলের মধু - PureGhor Black Seed Honey',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/778160023_1968999603762127_8330157447235278502_n.jpeg',
        alt: 'PureGhor মধু ও নাটস কালেকশন',
      },
    ],
    ingredients: '১০০% প্রাকৃতিক কালোজিরা ফুলের মধু।',
    nutrition: 'অ্যান্টিঅক্সিডেন্ট, খনিজ ও প্রাকৃতিক ফ্রুক্টোজ সমৃদ্ধ প্রাকৃতিক শক্তিদায়ক।',
    source: 'নাটোর ও সুন্দরবন উপকূলীয় অঞ্চলের মৌ খামার।',
    storageInstruction: 'স্বাভাবিক তাপমাত্রায় শুষ্ক স্থানে মুখ বন্ধ করে রাখুন। ফ্রিজে রাখবেন না।',
    expiryText: 'উৎপাদনের তারিখ থেকে ২ বছর পর্যন্ত চমৎকার থাকে।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-honey-nut', 'prod-kalijira-oil'],
    seoTitle: 'খাঁটি কালোজিরা ফুলের মধু - PureGhor',
    seoDescription: '১০০% খাঁটি ও প্রাকৃতিক কালোজিরা ফুলের মধু। হোম ডেলিভারি ক্যাশ অন ডেলিভারিতে।',
    rating: 5.0,
    reviewCount: 48,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-honey-nut',
    nameBn: 'প্রিমিয়াম হানি নাট জার (Honey Nut Extra Energy)',
    nameEn: 'Premium Honey Nut Energy Jar',
    slug: 'premium-honey-nut-jar',
    sku: 'PG-HNY-NUT',
    categoryId: 'cat-honey',
    shortDescriptionBn: 'কাজু বাদাম, কাঠ বাদাম, পেস্তা, আখরোট, গোল্ডেন কিসমিস ও খাঁটি মধুর পুষ্টিকর মিশ্রণ।',
    descriptionBn: 'শারীরিক দুর্বলতা দূর করতে এবং তাৎক্ষণিক পুষ্টি ও শক্তির জোগান দিতে PureGhor-এর স্পেশাল হানি নাট। প্রিমিয়াম গ্রেডের ড্রাই ফ্রুটস ও খাঁটি মধুর সুষম মেলবন্ধন। শিশু থেকে বয়স্ক সবার প্রিয় স্বাস্থ্যকর খাবার।',
    price: 980,
    salePrice: 850,
    currency: 'BDT',
    stock: 65,
    lowStockThreshold: 15,
    weight: 500,
    unit: 'gm',
    weightOptions: [
      { weight: 500, unit: 'gm', price: 980, salePrice: 850, stock: 65, sku: 'PG-HNUT-500' },
      { weight: 1, unit: 'kg', price: 1850, salePrice: 1650, stock: 25, sku: 'PG-HNUT-1KG' },
    ],
    images: [
      {
        url: '/images/uploaded/img4.jpg',
        alt: 'প্রিমিয়াম হানি নাট জার PureGhor Honey Nut',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/777916124_1726477055273195_4515666685499235866_n.jpeg',
        alt: 'খাঁটি মধু ও বাদামের মিশ্রণ',
      },
    ],
    ingredients: 'খাঁটি মধু, কাজু বাদাম, কাঠ বাদাম, আখরোট, পেস্তা বাদাম, গোল্ডেন কিসমিস, কুমড়ো বীজ ও কালোজিরা।',
    nutrition: 'হাই-প্রোটিন, গুড ফ্যাট, ভিটামিন ই, আয়রন ও জিংক সমৃদ্ধ।',
    source: 'PureGhor নিজস্ব হাইজেনিক প্রোডাকশন ও প্রিমিয়াম ড্রাই ফ্রুটস।',
    storageInstruction: 'শুষ্ক ও ঠান্ডা জায়গায় মুখ ভালো করে আটকে রাখুন।',
    expiryText: 'প্রস্তুতের তারিখ থেকে ৬ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-nut-combo', 'prod-akhrot'],
    seoTitle: 'প্রিমিয়াম হানি নাট জার - PureGhor',
    seoDescription: 'খাঁটি মধু ও বাদামে তৈরি প্রিমিয়াম হানি নাট। স্বাস্থ্য ও শক্তিবর্ধক পুষ্টিকর খাবার।',
    rating: 4.9,
    reviewCount: 39,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-nut-combo',
    nameBn: '৪ জার মেগা বাদাম ও বীজ স্বাস্থ্য কম্বো (টোটাল ১ কেজি)',
    nameEn: '4-Jar Premium Nut & Seed Super Combo (1 KG)',
    slug: 'four-jar-nut-seed-combo',
    sku: 'PG-CMB-4NUT',
    categoryId: 'cat-nuts-seeds',
    shortDescriptionBn: 'কাঠ বাদাম (২৫০ গ্রাম) + কাজু বাদাম (২৫০ গ্রাম) + গোল্ডেন কিসমিস (২৫০ গ্রাম) + মিষ্টি কুমড়ো বীজ (২৫০ গ্রাম)।',
    descriptionBn: 'আপনার পরিবারের প্রতিদিনের ভিটামিন, মিনারেল ও স্বাস্থ্য সুরক্ষায় ৪টি প্রিমিয়াম জারের ধামাকা কম্বো অফার! আলাদা কেনার চেয়ে কম্বোতে পাচ্ছেন বিশাল সাশ্রয় ও চমৎকার ফ্রেশ ক্রিস্পি স্বাদ।',
    price: 1650,
    salePrice: 1390,
    currency: 'BDT',
    stock: 40,
    lowStockThreshold: 8,
    weight: 1,
    unit: 'kg',
    images: [
      {
        url: '/images/uploaded/img7.jpg',
        alt: '৪ জার স্পেশাল বাদাম ও বীজ কম্বো PureGhor Nut Combo',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/738465049_1960823601232100_4535246048439465719_n.jpeg',
        alt: '৪ জার স্পেশাল কম্বো প্যাক',
      },
    ],
    ingredients: 'কাঠ বাদাম ২৫০ গ্রাম, কাজু বাদাম ২৫০ গ্রাম, গোল্ডেন কিসমিস ২৫০ গ্রাম, মিষ্টি কুমড়ো বীজ ২৫০ গ্রাম।',
    nutrition: 'উচ্চমানের প্ল্যান্ট প্রোটিন, ম্যাগনেসিয়াম, পটাশিয়াম ও ওমেগা ফ্যাটি অ্যাসিড।',
    source: 'গ্রেড-১ প্রিমিয়াম আমদানিকৃত খাদ্যশস্য ও ড্রাইড ফ্রুটস।',
    storageInstruction: 'প্রতিটি কাচের জারের ক্যাপ ভালোভাবে আটকে শুকনো স্থানে রাখুন।',
    expiryText: 'প্যাকেজিং থেকে ১২ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-akhrot', 'prod-honey-nut'],
    seoTitle: '৪ জার বাদাম ও কিসমিস কম্বো অফার - PureGhor',
    seoDescription: 'কাঠ বাদাম, কাজু বাদাম, কিসমিস ও কুমড়ো বীজের ১ কেজি সাশ্রয়ী কম্বো প্যাক।',
    rating: 5.0,
    reviewCount: 62,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-akhrot',
    nameBn: 'প্রিমিয়াম খোসা ছাড়া আখরোট (Brain Food Walnuts)',
    nameEn: 'Premium Raw Shelled Walnuts',
    slug: 'premium-walnut-akhrot',
    sku: 'PG-NUT-AKHROT',
    categoryId: 'cat-nuts-seeds',
    shortDescriptionBn: 'মস্তিষ্কের পুষ্টি ও হার্টের সুরক্ষায় ওমেগা-৩ ফ্যাটি এসিডে ভরপুর ফ্রেশ আস্ত আখরোট।',
    descriptionBn: 'আখরোটকে বলা হয় প্রকৃতির ব্রেন ফুড। স্মৃতিশক্তি বৃদ্ধি, হার্টের কোলেস্টেরল নিয়ন্ত্রণ এবং ত্বকের উজ্জ্বলতায় প্রতিদিন ২-৩টি আখরোট অত্যন্ত কার্যকরী। কোনো গন্ধ বা পুরানো তিতকুটে ভাব ছাড়া সম্পূর্ণ তাজা ও ক্রাঞ্চি।',
    price: 650,
    salePrice: 580,
    currency: 'BDT',
    stock: 45,
    lowStockThreshold: 10,
    weight: 250,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 650, salePrice: 580, stock: 45, sku: 'PG-WNT-250' },
      { weight: 500, unit: 'gm', price: 1250, salePrice: 1100, stock: 25, sku: 'PG-WNT-500' },
    ],
    images: [
      {
        url: '/images/uploaded/img8.jpg',
        alt: 'প্রিমিয়াম আখরোট - PureGhor Premium Walnuts',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/779050252_2644299516029094_7573122435296028448_n.jpeg',
        alt: 'খোসা ছাড়ানো ফ্রেশ আখরোট',
      },
    ],
    ingredients: '১০০% খোসা ছাড়ানো আস্ত কাঁচা আখরোট।',
    nutrition: 'ওমেগা-৩ (ALA), প্রোটিন, ভিটামিন বি-৬ ও অ্যান্টিঅক্সিডেন্ট।',
    source: 'আমেরিকা ও কাশ্মীরের নির্বাচিত বাগান থেকে সংগৃহীত।',
    storageInstruction: 'স্বাভাবিক শুষ্ক তাপমাত্রায় বা রেফ্রিজারেটরে বায়ুরোধী পাত্রে রাখুন।',
    expiryText: 'প্যাকেজিং থেকে ৯ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-nut-combo', 'prod-honey-nut'],
    seoTitle: 'খাঁটি প্রিমিয়াম আখরোট - PureGhor',
    seoDescription: 'স্মৃতিশক্তি ও হার্ট সুরক্ষায় প্রিমিয়াম ক্রাঞ্চি আখরোট।',
    rating: 4.9,
    reviewCount: 22,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-balachao',
    nameBn: 'স্পেশাল হোমমেড ক্রিস্পি চিংড়ি বালাচাও (Spicy Shrimp Balachao)',
    nameEn: 'Authentic Crispy Homemade Shrimp Balachao',
    slug: 'authentic-shrimp-balachao',
    sku: 'PG-SPC-BALACHAO',
    categoryId: 'cat-spices-special',
    shortDescriptionBn: 'কক্সবাজারের ফ্রেশ শুকনো চিংড়ি, ভাজা পেঁয়াজ ও খাঁটি মসলায় তৈরি মুখরোচক ক্রিস্পি বালাচাও।',
    descriptionBn: 'মুখরোচক স্বাদের ঐতিহ্যবাহী খাবার চিংড়ি বালাচাও। গরম ভাত, খিচুড়ি কিংবা রুটির সাথে চমৎকার জমে ওঠে। শতভাগ ঘরোয়া পরিবেশে খাঁটি সরিষার তেলে মুচমুচে করে ভাজা, কোনো ক্ষতিকর কৃত্রিম ফ্লেভার বা রাসায়নিক ছাড়াই তৈরি।',
    price: 450,
    salePrice: 390,
    currency: 'BDT',
    stock: 55,
    lowStockThreshold: 10,
    weight: 200,
    unit: 'gm',
    weightOptions: [
      { weight: 200, unit: 'gm', price: 450, salePrice: 390, stock: 55, sku: 'PG-BLC-200' },
      { weight: 400, unit: 'gm', price: 850, salePrice: 750, stock: 20, sku: 'PG-BLC-400' },
    ],
    images: [
      {
        url: '/images/uploaded/img9.jpg',
        alt: 'স্পেশাল ক্রিস্পি চিংড়ি বালাচাও PureGhor Shrimp Balachao',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/740259912_853043360933083_8062257320957614052_n.jpeg',
        alt: 'ঘরোয়া ক্রিস্পি বালাচাও',
      },
    ],
    ingredients: 'শুকনো দেশি ছোট চিংড়ি, ভাজা পেঁয়াজ, রসুন, লাল মরিচ, সরিষার তেল ও বিশেষ মসলা।',
    nutrition: 'উচ্চমানের সামুদ্রিক প্রোটিন ও ক্যালসিয়াম সমৃদ্ধ।',
    source: 'কক্সবাজারের ফ্রেশ চিংড়ি থেকে নিজস্ব কিচেনে স্বাস্থ্যসম্মতভাবে প্রস্তুত।',
    storageInstruction: 'শুকনো চামচ ব্যবহার করুন এবং বাতাস ঢোকা বন্ধ রাখতে জারের মুখ শক্ত করে লাগান।',
    expiryText: 'প্রস্তুতের তারিখ থেকে ৪ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-honey-kalijira', 'prod-nut-combo'],
    seoTitle: 'খাঁটি ক্রিস্পি চিংড়ি বালাচাও - PureGhor',
    seoDescription: 'ঘরোয়া স্বাদের মুচমুচে চিংড়ি বালাচাও। গরম ভাতে অতুলনীয় তৃপ্তি।',
    rating: 5.0,
    reviewCount: 31,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-kalijira-oil',
    nameBn: 'প্রাকৃতিক জয়েন্ট কেয়ার ও খাঁটি কালোজিরা তেল (১০০% কোল্ড-প্রেসড)',
    nameEn: 'Pure Black Seed Oil & Natural Joint Care',
    slug: 'pure-kalijira-oil-joint-care',
    sku: 'PG-OIL-KALIJIRA',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'প্রকৃতির শক্তিতে জয়েন্ট ও পেশির ব্যথানাশক খাঁটি কালোজিরার কোল্ড-প্রেসড তেল।',
    descriptionBn: 'মৃত্যু ব্যতীত সর্বরোগের মহৌষধ কালোজিরা। খাঁটি প্রথম চাপের এই কালোজিরা তেল জয়েন্টের ব্যথা, বাত, ঠান্ডাজনিত সমস্যা উপশমে ম্যাসাজ এবং খাওয়ার জন্য উপযুক্ত। কোনো প্রকার ভেজাল মিশ্রণ ছাড়া তৈরি।',
    price: 380,
    salePrice: 320,
    currency: 'BDT',
    stock: 60,
    lowStockThreshold: 12,
    weight: 100,
    unit: 'ml',
    weightOptions: [
      { weight: 100, unit: 'ml', price: 380, salePrice: 320, stock: 60, sku: 'PG-KJO-100' },
      { weight: 250, unit: 'ml', price: 850, salePrice: 750, stock: 30, sku: 'PG-KJO-250' },
    ],
    images: [
      {
        url: '/images/uploaded/img6.jpg',
        alt: 'প্রকৃতির শক্তিতে জয়েন্টের যত্ন কালোজিরা তেল PureGhor Black Seed Oil',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/778972309_1922577025083385_4765835242500284291_n.jpeg',
        alt: 'কোল্ড প্রেসড কালোজিরা তেল বোতল',
      },
    ],
    ingredients: '১০০% খাঁটি কোল্ড-প্রেসড কালোজিরা তেল।',
    nutrition: 'থাইমোকুইনোন (Thymoquinone), অ্যান্টি-ইনফ্ল্যামেটরি উপাদান সমৃদ্ধ।',
    source: 'নাটোরের খাঁটি কালোজিরা থেকে কাঠের ঘানিতে মৃদু চাপে নিষ্কাশিত।',
    storageInstruction: 'সরাসরি সূর্যের আলো থেকে দূরে শুষ্ক ও ঠান্ডা স্থানে সংরক্ষণ করুন।',
    expiryText: 'বোতলজাত করার তারিখ থেকে ১৮ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-honey-kalijira', 'prod-4', 'prod-olive-oil'],
    seoTitle: 'খাঁটি কালোজিরা তেল ও জয়েন্ট কেয়ার - PureGhor',
    seoDescription: '১০০% খাঁটি কোল্ড-প্রেসড কালোজিরা তেল। ব্যথানাশক ও স্বাস্থ্য সুরক্ষায়।',
    rating: 4.9,
    reviewCount: 27,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-olive-oil',
    nameBn: 'প্রিমিয়াম স্প্যানিশ এক্সট্রা ভার্জিন অলিভ অয়েল (Blends of Spanish Olive Oil)',
    nameEn: 'PureGhor Extra Virgin Spanish Olive Oil',
    slug: 'spanish-extra-virgin-olive-oil',
    sku: 'PG-OIL-OLIVE',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'স্পেনের নির্বাচিত জলপাই থেকে কোল্ড-প্রেসড প্রথম চাপের খাঁটি এক্সট্রা ভার্জিন অলিভ অয়েল।',
    descriptionBn: 'স্পেনের ঐতিহ্যবাহী বাগান থেকে সরাসরি আমদানিকৃত প্রিমিয়াম ব্লেন্ডের অলিভ অয়েল। সালাদ ড্রেসিং, ত্বক ও চুলের যত্ন এবং স্বাস্থ্যকর রান্নায় অত্যন্ত উপযোগী। উচ্চমাত্রার অ্যান্টিঅক্সিডেন্ট ও স্বাস্থ্যকর মনোআনস্যাচুরেটেড ফ্যাট সমৃদ্ধ।',
    price: 950,
    salePrice: 850,
    currency: 'BDT',
    stock: 45,
    lowStockThreshold: 10,
    weight: 500,
    unit: 'ml',
    weightOptions: [
      { weight: 250, unit: 'ml', price: 520, salePrice: 470, stock: 30, sku: 'PG-OLV-250' },
      { weight: 500, unit: 'ml', price: 950, salePrice: 850, stock: 45, sku: 'PG-OLV-500' },
      { weight: 1, unit: 'ltr', price: 1750, salePrice: 1580, stock: 20, sku: 'PG-OLV-1L' },
    ],
    images: [
      {
        url: '/images/uploaded/img11.jpg',
        alt: 'PureGhor Spanish Olive Oil স্প্যানিশ অলিভ অয়েল',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% খাঁটি স্প্যানিশ এক্সট্রা ভার্জিন অলিভ অয়েল।',
    nutrition: 'ওলিক অ্যাসিড, পলিফেনল, ভিটামিন ই ও ভিটামিন কে সমৃদ্ধ।',
    source: 'স্পেন থেকে সরাসরি আমদানিকৃত প্রিমিয়াম অলিভ।',
    storageInstruction: 'সরাসরি রোদ ও তাপ থেকে দূরে শুষ্ক ঠান্ডা স্থানে রাখুন।',
    expiryText: 'বোতলজাতের তারিখ থেকে ২৪ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-kalijira-oil', 'prod-2'],
    seoTitle: 'স্প্যানিশ এক্সট্রা ভার্জিন অলিভ অয়েল - PureGhor',
    seoDescription: 'খাঁটি স্প্যানিশ অলিভ অয়েল সালাদ ও সুস্বাস্থ্যের জন্য।',
    rating: 5.0,
    reviewCount: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-quaker-oats-pouch',
    nameBn: 'কোয়েকার ওটস ব্লু পাউচ ৯০০ গ্রাম (Quaker Oats)',
    nameEn: 'Quaker White Oats 900g Pouch',
    slug: 'quaker-oats-pouch-900g',
    sku: 'PG-OAT-QUAKER900',
    categoryId: 'cat-oats',
    shortDescriptionBn: '১০০% হোল গ্রেইন ওটস, হার্টের স্বাস্থ্য ও ওজন নিয়ন্ত্রণে আদর্শ সকালের পুষ্টিকর নাস্তা।',
    descriptionBn: 'বিশ্ববিখ্যাত কোয়েকার ব্র্যান্ডের ১০০% হোল গ্রেইন ওটস। এটি দ্রবণীয় ফাইবার বিটা-গ্লুকানে সমৃদ্ধ যা রক্তের কোলেস্টেরল নিয়ন্ত্রণে সহায়তা করে এবং দীর্ঘক্ষণ পেট ভরা রাখে। দুধ, ফল বা পানির সাথে সহজেই রান্না করা যায়।',
    price: 680,
    salePrice: 620,
    currency: 'BDT',
    stock: 45,
    lowStockThreshold: 10,
    weight: 900,
    unit: 'gm',
    images: [
      {
        url: '/images/pureghor/722119294_1968026900508945_6535640957699175289_n.jpeg',
        alt: 'কোয়েকার ওটস পাউচ ৯০০ গ্রাম',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/773379069_3439225979589311_6435072898136566028_n.jpeg',
        alt: 'কোয়েকার ওটস কন্টেইনার কালেকশন',
      },
    ],
    ingredients: '১০০% হোল গ্রেইন রোল্ড ওটস।',
    nutrition: 'উচ্চ ডায়েটারি ফাইবার, আয়রন ও কমপ্লেক্স কার্বোহাইড্রেট।',
    source: 'আন্তর্জাতিক আমদানিকৃত গ্রেড-১ ওটস।',
    storageInstruction: 'প্যাকেট খোলার পর শুষ্ক ও বায়ুরোধী পাত্রে সংরক্ষণ করুন।',
    expiryText: 'প্যাকেটের গায়ে উল্লেখিত মেয়াদ দেখুন।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-ausimex-oats', 'prod-organic-baby-oats'],
    seoTitle: 'কোয়েকার ওটস ৯০০ গ্রাম - PureGhor',
    seoDescription: '১০০% হোল গ্রেইন কোয়েকার ওটস। স্বাস্থ্যসম্মত সকালের নাস্তার জন্য সেরা।',
    rating: 4.8,
    reviewCount: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-ausimex-oats',
    nameBn: 'অসিমেক্স অস্ট্রেলিয়ান বেবি ওটস ৫০০ গ্রাম (AUSIMEX Baby Oats)',
    nameEn: 'AUSIMEX Australian Baby Oats 500g',
    slug: 'ausimex-baby-oats',
    sku: 'PG-OAT-AUSIMEX',
    categoryId: 'cat-oats',
    shortDescriptionBn: 'অস্ট্রেলিয়ার খাঁটি ওটস থেকে তৈরি কোমল ও সহজে হজমযোগ্য পুষ্টিকর বেবি ওটস।',
    descriptionBn: 'শিশুদের প্রথম সলিড খাবার এবং বড়দের জন্য হালকা ও সুস্বাদু ব্রেকফাস্টের জন্য অসিমেক্স বেবি ওটস আদর্শ। এটি অত্যন্ত দ্রুত রান্না হয় এবং সহজে হজম হয়।',
    price: 390,
    salePrice: 350,
    currency: 'BDT',
    stock: 50,
    lowStockThreshold: 10,
    weight: 500,
    unit: 'gm',
    images: [
      {
        url: '/images/pureghor/731111473_1923805098282637_932601733845508970_n.jpeg',
        alt: 'AUSIMEX অস্ট্রেলিয়ান বেবি ওটস ৫০০ গ্রাম',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/732597014_2074558540609712_8558507915178937195_n.jpeg',
        alt: 'অর্গানিক ওটস কালেকশন',
      },
    ],
    ingredients: '১০০% অস্ট্রেলিয়ান ওটস।',
    nutrition: 'সমৃদ্ধ ফাইবার, আয়রন, ভিটামিন বি ও প্রোটিন।',
    source: 'অস্ট্রেলিয়া থেকে আমদানিকৃত।',
    storageInstruction: 'শুকনো ও ঠান্ডা স্থানে রাখুন।',
    expiryText: 'প্যাকেটের গায়ে উল্লেখিত মেয়াদ।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-quaker-oats-pouch', 'prod-organic-baby-oats'],
    seoTitle: 'অসিমেক্স অস্ট্রেলিয়ান বেবি ওটস - PureGhor',
    seoDescription: 'শিশুদের স্বাস্থ্যকর খাবারের জন্য অসিমেক্স অস্ট্রেলিয়ান বেবি ওটস।',
    rating: 4.9,
    reviewCount: 16,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-organic-baby-oats',
    nameBn: 'হেলথ প্যারাডাইস অর্গানিক বেবি ওটস ৫০০ গ্রাম (Health Paradise)',
    nameEn: 'Health Paradise Organic Baby Oats 500g',
    slug: 'health-paradise-organic-baby-oats',
    sku: 'PG-OAT-HP-BABY',
    categoryId: 'cat-oats',
    shortDescriptionBn: 'USDA সার্টিফাইড অর্গানিক বেবি ওটস, কোনো প্রিজারভেটিভ বা কেমিক্যাল ছাড়া তৈরি।',
    descriptionBn: 'সম্পূর্ণ অর্গানিক উপায়ে চাষকৃত ওটস থেকে তৈরি হেলথ প্যারাডাইস বেবি ওটস। এটি শিশুর সঠিক বিকাশ ও পারিবারিক পুষ্টিতে অতুলনীয় ভূমিকা রাখে।',
    price: 460,
    salePrice: 410,
    currency: 'BDT',
    stock: 35,
    lowStockThreshold: 8,
    weight: 500,
    unit: 'gm',
    images: [
      {
        url: '/images/pureghor/773272133_1401762758532350_450888033961899514_n.jpeg',
        alt: 'হেলথ প্যারাডাইস অর্গানিক বেবি ওটস',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/732597014_2074558540609712_8558507915178937195_n.jpeg',
        alt: 'অর্গানিক ওটস প্যাকেজিং',
      },
    ],
    ingredients: '১০০% সার্টিফাইড অর্গানিক ওটস।',
    nutrition: 'প্রাকৃতিক ডায়েটারি ফাইবার, নো কেমিক্যাল বা কৃত্রিম উপাদান।',
    source: 'অস্ট্রেলিয়া / মালয়েশিয়া আমদানিকৃত অর্গানিক প্রোডাক্ট।',
    storageInstruction: 'শুকনো ও রোদহীন জায়গায় রাখুন।',
    expiryText: 'প্যাকেটের গায়ে উল্লেখিত মেয়াদ।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-ausimex-oats', 'prod-oat-choco'],
    seoTitle: 'হেলথ প্যারাডাইস অর্গানিক বেবি ওটস - PureGhor',
    seoDescription: '১০০% অর্গানিক সার্টিফাইড বেবি ওটস। শিশুর জন্য নিরাপদ ও পুষ্টিকর।',
    rating: 5.0,
    reviewCount: 14,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-oat-choco',
    nameBn: 'টিকিউ ওট চকো এনার্জি ক্রিস্পি বার (TQ Oat Choco)',
    nameEn: 'TQ Oat Choco Crispy Energy Snack',
    slug: 'tq-oat-choco-energy-bar',
    sku: 'PG-OAT-CHOCO',
    categoryId: 'cat-oats',
    shortDescriptionBn: 'সুস্বাদু চকোলেট ও ওটসের মুচমুচে ক্রিস্পি এনার্জি বাইট ও স্ন্যাক্স।',
    descriptionBn: 'বাচ্চা ও বড়দের প্রিয় পুষ্টিকর ও চটজলদি হেলদি স্ন্যাক্স টিকিউ ওট চকো। ওটসের পুষ্টি ও চকোলেটের মুখরোচক স্বাদের চমৎকার কম্বিনেশন। স্কুল টিফিন ও অফিসের নাস্তার জন্য দারুণ।',
    price: 360,
    salePrice: 320,
    currency: 'BDT',
    stock: 50,
    lowStockThreshold: 10,
    weight: 400,
    unit: 'gm',
    images: [
      {
        url: '/images/pureghor/772586170_1061124710183074_5904727855206132038_n.jpeg',
        alt: 'টিকিউ ওট চকো এনার্জি স্ন্যাক্স PureGhor',
        isPrimary: true,
      },
    ],
    ingredients: 'ওটস ফ্লেক্স, কোকো সলিডস, মিল্ক পাউডার, চিনি ও উদ্ভিজ্জ তেল।',
    nutrition: 'ইনস্ট্যান্ট এনার্জি ও ফাইবার সমৃদ্ধ স্ন্যাক্স।',
    source: 'আন্তর্জাতিক আমদানিকৃত গ্রেড কোয়ালিটি।',
    storageInstruction: 'ঠান্ডা ও শুষ্ক স্থানে রাখুন।',
    expiryText: 'প্যাকেটের গায়ে উল্লেখিত মেয়াদ পর্যন্ত।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-quaker-oats-pouch', 'prod-honey-nut'],
    seoTitle: 'টিকিউ ওট চকো এনার্জি স্ন্যাক্স - PureGhor',
    seoDescription: 'ওটস ও চকোলেটের পুষ্টিকর স্ন্যাক্স টিফিন ও নাস্তার জন্য।',
    rating: 4.7,
    reviewCount: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-mangoes',
    nameBn: 'রাসায়নিকমুক্ত তাজা কাঁচা ও পাকা আম (মৌসুমি ফল)',
    nameEn: 'Fresh Chemical-Free Green & Ripe Mangoes',
    slug: 'fresh-chemical-free-mangoes',
    sku: 'PG-FRT-MANGO',
    categoryId: 'cat-spices-special',
    shortDescriptionBn: 'বাগান থেকে সরাসরি বাছাইকৃত কোনো কার্বাইড বা ফরমালিন ছাড়া খাঁটি তাজা আম।',
    descriptionBn: 'PureGhor-এর মৌসুমি ফ্রেশ ফ্রুটস কালেকশন। সরাসরি বাগান থেকে পেড়ে ডেলিভারি দেওয়া হয়, কোনো প্রকার কেমিক্যাল বা পাকানোর স্প্রে ছাড়া। আচার তৈরি ও তাজা খাওয়ার জন্য অতুলনীয়।',
    price: 320,
    salePrice: 280,
    currency: 'BDT',
    stock: 40,
    lowStockThreshold: 10,
    weight: 2,
    unit: 'kg',
    images: [
      {
        url: '/images/pureghor/731067967_1165096542480498_5504005484939299210_n.jpeg',
        alt: 'বাগান থেকে তাজা কাঁচা আম PureGhor',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/732103407_2085145489018609_7477184784061194606_n.jpeg',
        alt: 'ফ্রেশ আমের খাঁচা PureGhor',
      },
    ],
    ingredients: '১০০% গাছপাকা / কাঁচা প্রাকৃতিক আম।',
    nutrition: 'ভিটামিন সি, ভিটামিন এ ও প্রাকৃতিক ডায়েটারি ফাইবার।',
    source: 'রাজশাহী ও সাতক্ষীরার নিজস্ব চুক্তিবদ্ধ আমবাগান।',
    storageInstruction: 'খোলা বাতাসে বা নরমাল তাপমাত্রায় সংরক্ষণ করুন।',
    expiryText: 'তাজা সংগ্রহের পর ৭-১০ দিন।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-balachao', 'prod-honey-kalijira'],
    seoTitle: 'কেমিক্যালমুক্ত তাজা আম - PureGhor',
    seoDescription: 'সরাসরি বাগান থেকে ফরমালিনমুক্ত তাজা কাঁচা ও পাকা আম।',
    rating: 4.9,
    reviewCount: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    nameBn: 'ঐতিহ্যবাহী দানাদার গাওয়া ঘি (সিরাজগঞ্জ)',
    nameEn: 'Traditional Cow Ghee (Sirajganj)',
    slug: 'traditional-cow-ghee',
    sku: 'PG-GHEE-001',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'সিরাজগঞ্জের মাঠা থেকে মাখন তুলে জ্বাল দিয়ে তৈরি দানাদার সুগন্ধি গাওয়া ঘি।',
    descriptionBn: 'আমাদের গাওয়া ঘি খাঁটি দেশি গাভীর দুধের মাখন থেকে তৈরি। ঐতিহ্যবাহী পদ্ধতিতে মৃদু আঁচে জ্বাল দেওয়া হয়, যা এনে দেয় চমৎকার সোনালী দানাদার টেক্সচার ও মন মাতানো সুবাস। গরম ভাত, খিচুড়ি কিংবা রান্নায় অনন্য স্বাদ যুক্ত করে।',
    price: 900,
    salePrice: 820,
    currency: 'BDT',
    stock: 35,
    lowStockThreshold: 8,
    weight: 500,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 480, salePrice: 430, stock: 25, sku: 'PG-GHEE-001-250' },
      { weight: 500, unit: 'gm', price: 900, salePrice: 820, stock: 35, sku: 'PG-GHEE-001-500' },
      { weight: 1, unit: 'kg', price: 1750, salePrice: 1600, stock: 15, sku: 'PG-GHEE-001-1KG' },
    ],
    images: [
      {
        url: '/images/pureghor/731843570_3182118701988973_854022805183807248_n.jpeg',
        alt: 'দানাদার সোনালী গাওয়া ঘি',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% দেশি গাভীর দুধের মাখন।',
    nutrition: 'প্রতি ১০০ গ্রামে: ক্যালোরি ৯০০ kcal, ফ্যাট ৯৯.৫%, ওমেগা-৩ ও ওমেগা-৯ ফ্যাটি এসিড।',
    source: 'সিরাজগঞ্জের বাঘাবাড়ি ও শাহজাদপুর অঞ্চলের গো-খামার।',
    storageInstruction: 'আলো থেকে দূরে স্বাভাবিক তাপমাত্রায় শুকনো চামচ ব্যবহার করে সংরক্ষণ করুন।',
    expiryText: 'প্যাকেজিং এর পর থেকে ৯ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-honey-kalijira', 'prod-4'],
    seoTitle: 'খাঁটি গাওয়া ঘি - দানাদার ও সুগন্ধি | PureGhor',
    seoDescription: 'খাঁটি গাওয়া ঘি সিরাজগঞ্জ থেকে সংগৃহীত। ভেজালহীন সোনালী দানাদার ঘি।',
    rating: 5.0,
    reviewCount: 34,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    nameBn: 'কাঠের ঘানিতে ভাঙানো খাঁটি সরিষার তেল',
    nameEn: 'Cold-Pressed Mustard Oil (Wood Churn)',
    slug: 'cold-pressed-mustard-oil',
    sku: 'PG-OIL-001',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'দেশি মাঘী সরিষা থেকে কাঠের ঘানিতে ধীরগতিতে ভাঙানো প্রথম চাপের ঝাঁঝালো তেল।',
    descriptionBn: 'ধীরগতির কাঠের ঘানিতে ভাঙানোর ফলে তেলের তাপমাত্রা বৃদ্ধি পায় না, যার ফলে সরিষার সমস্ত প্রাকৃতিক পুষ্টিগুণ, ঝাঁঝ ও চমৎকার গন্ধ অটুট থাকে। কোনো প্রকার কেমিক্যাল বা পরিশোধনের স্পর্শ নেই।',
    price: 360,
    salePrice: 320,
    currency: 'BDT',
    stock: 50,
    lowStockThreshold: 15,
    weight: 1,
    unit: 'ltr',
    weightOptions: [
      { weight: 500, unit: 'ml', price: 190, salePrice: 170, stock: 40, sku: 'PG-OIL-001-500' },
      { weight: 1, unit: 'ltr', price: 360, salePrice: 320, stock: 50, sku: 'PG-OIL-001-1L' },
      { weight: 5, unit: 'ltr', price: 1750, salePrice: 1550, stock: 15, sku: 'PG-OIL-001-5L' },
    ],
    images: [
      {
        url: '/images/pureghor/772218375_2009050126395720_4862285561095726924_n.jpeg',
        alt: 'কাঠের ঘানির খাঁটি সরিষার তেল কাচের বোতলে',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% দেশি মাঘী সরিষা।',
    nutrition: 'মনোআনস্যাচুরেটেড ফ্যাটি এসিড, ওমেগা-৩ ও ওমেগা-৬ ব্যালেন্স সমৃদ্ধ।',
    source: 'মানিকগঞ্জ ও সিরাজগঞ্জের নিজস্ব তত্ত্বাবধানে পরিচালিত কাঠের ঘানি।',
    storageInstruction: 'সরাসরি রোদ থেকে দূরে ঠান্ডা ও অন্ধকার স্থানে রাখুন।',
    expiryText: 'ভাঙানোর তারিখ থেকে ১২ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-2', 'prod-kalijira-oil'],
    seoTitle: 'কাঠের ঘানির খাঁটি সরিষার তেল | PureGhor',
    seoDescription: 'প্রাকৃতিক ঝাঁঝালো সরিষার তেল কাঠের ঘানিতে ভাঙানো। স্বাস্থ্যসম্মত রান্নার তেল।',
    rating: 4.9,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    nameBn: 'যশোরের স্পেশাল ঝোলা খেজুর গুড়',
    nameEn: 'Jashore Special Date Palm Liquid Gur',
    slug: 'jashore-khejurer-jhola-gur',
    sku: 'PG-GUR-001',
    categoryId: 'cat-gur',
    shortDescriptionBn: 'যশোরের তাজা খেজুরের রস থেকে কোনো কেমিক্যাল ছাড়া জ্বাল দেওয়া নলেন ঝোলা গুড়।',
    descriptionBn: 'খেজুরের গুড়ের রাজধানী যশোর থেকে সরাসরি সংগৃহীত। শীতের ভোরে নামানো মিষ্টি রস দিয়ে ঐতিহ্যবাহী মাটির চুলায় ঘন করে জ্বাল দেওয়া এই ঝোলা গুড়। পিঠা, পায়েস ও রুটির সাথে অতুলনীয়।',
    price: 450,
    salePrice: 390,
    currency: 'BDT',
    stock: 60,
    lowStockThreshold: 12,
    weight: 1,
    unit: 'kg',
    images: [
      {
        url: '/images/pureghor/772513850_1055475870270979_5142302322816849426_n.jpeg',
        alt: 'যশোরের সুস্বাদু নলেন ঝোলা গুড় মাটির হাঁড়িতে',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% প্রাকৃতিক খেজুরের রস। সোডা ও হাইড্রোস মুক্ত।',
    nutrition: 'আয়রন, ম্যাগনেসিয়াম, পটাশিয়াম ও অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ।',
    source: 'যশোরের খাজুরা ও বাঘারপাড়া অঞ্চল।',
    storageInstruction: 'স্বাভাবিক তাপমাত্রায় অথবা রেফ্রিজারেটরে সংরক্ষণ করুন।',
    expiryText: '৬ মাস পর্যন্ত ভালো থাকে।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-2', 'prod-honey-kalijira'],
    seoTitle: 'যশোরের খাঁটি খেজুরের গুড় - PureGhor',
    seoDescription: 'কেমিক্যালমুক্ত খাঁটি খেজুরের ঝোলা গুড়। পিঠা ও পায়েসের আসল স্বাদ।',
    rating: 4.8,
    reviewCount: 19,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    nameBn: 'প্রিমিয়াম অর্গানিক চিয়া সিড (USDA Certified)',
    nameEn: 'Organic Chia Seeds (USDA Certified)',
    slug: 'organic-chia-seeds',
    sku: 'PG-SEED-001',
    categoryId: 'cat-spices-special',
    shortDescriptionBn: 'উচ্চমানের ডায়েটারি ফাইবার ও ওমেগা-৩ ফ্যাটি এসিড সমৃদ্ধ আমদানিকৃত প্রিমিয়াম চিয়া বীজ।',
    descriptionBn: 'ওজন নিয়ন্ত্রণ, হজম শক্তি বৃদ্ধি এবং হার্ট সুস্থ রাখতে চিয়া সিডের জুড়ি নেই। শতভাগ ধুলাবালিমুক্ত এবং গ্রেড-১ মানের কালো চিয়া সিড। প্রতিদিন সকালে লেবুর পানি, স্মুদি বা ওটসের সাথে খাওয়ার উপযোগী।',
    price: 420,
    salePrice: 360,
    currency: 'BDT',
    stock: 40,
    lowStockThreshold: 10,
    weight: 250,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 420, salePrice: 360, stock: 40, sku: 'PG-SEED-001-250' },
      { weight: 500, unit: 'gm', price: 780, salePrice: 680, stock: 25, sku: 'PG-SEED-001-500' },
    ],
    images: [
      {
        url: '/images/uploaded/img5.jpg',
        alt: 'প্রিমিয়াম অর্গানিক চিয়া সিড PureGhor Chia Seeds',
        isPrimary: true,
      },
      {
        url: '/images/pureghor/757700374_1054100053804163_386722467757915465_n.jpeg',
        alt: 'প্রিমিয়াম ব্ল্যাক চিয়া সিড জারে',
      },
    ],
    ingredients: '১০০% অর্গানিক কালো চিয়া বীজ।',
    nutrition: 'প্রতি ১০০ গ্রামে ফাইবার ৩৪ গ্রাম, প্রোটিন ১৬.৫ গ্রাম, ওমেগা-৩ ১৭.৮ গ্রাম।',
    source: 'দক্ষিণ আমেরিকা থেকে সরাসরি আমদানিকৃত এবং ল্যাব-টেস্টেড।',
    storageInstruction: 'শুষ্ক ও ঠান্ডা স্থানে বাতাসমুক্ত বায়ুরোধী জারে রাখুন।',
    expiryText: 'প্যাকেজিং থেকে ১৮ মাস।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-honey-kalijira', 'prod-quaker-oats-pouch'],
    seoTitle: 'অর্গানিক চিয়া সিড - PureGhor',
    seoDescription: '১০০% পিওর ব্ল্যাক চিয়া সিড। ওজন নিয়ন্ত্রণ ও ফিটনেসের জন্য সুপারফুড।',
    rating: 4.8,
    reviewCount: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-hero-1',
    titleBn: 'শতভাগ খাঁটি ও প্রাকৃতিক খাদ্যের বিশ্বস্ত ঠিকানা - PureGhor',
    subtitleBn: 'বিশ্বনাথ ও লালাবাজার আউটলেট এবং অনলাইন অর্ডারে পাচ্ছেন নিশ্চিত সেরা কোয়ালিটি!',
    type: 'hero',
    imageUrl: '/images/uploaded/img2.jpg',
    altText: 'PureGhor ১০০% খাঁটি ও প্রাকৃতিক ফুড ব্যানার',
    targetUrl: '/shop',
    ctaTextBn: 'এখনই শপ করুন',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ban-hero-2',
    titleBn: 'সিলেটের বিখ্যাত ব্র্যান্ড PureGhor এখন বিশ্বনাথ ও লালাবাজার',
    subtitleBn: 'উদ্বোধন উপলক্ষে পাচ্ছেন আকর্ষণীয় ছাড় ও দ্রুততম হোম ডেলিভারি!',
    type: 'hero',
    imageUrl: '/images/uploaded/img1.jpg',
    altText: 'PureGhor বিশ্বনাথ ও লালাবাজার শোরুম ব্যানার',
    targetUrl: '/about-us',
    ctaTextBn: 'আমাদের আউটলেটে আসুন',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ban-offer-1',
    titleBn: 'PureGhor স্পেশাল অফার ও মেগা ডিসকাউন্ট প্যাকেজ',
    subtitleBn: 'মধু, বাদাম, কালোজিরা তেল ও অর্গানিক সুপারফুডে আকর্ষণীয় কম্বো ছাড়!',
    type: 'offer',
    imageUrl: '/images/uploaded/img10.jpg',
    altText: 'PureGhor স্পেশাল মেগা ডিসকাউন্ট অফার ব্যানার',
    targetUrl: '/shop',
    ctaTextBn: 'অফার উপভোগ করুন',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ban-offer-2',
    titleBn: 'PureGhor কোয়ালিটি গ্যারান্টি ও হটলাইন সেবা',
    subtitleBn: 'যে কোনো তথ্য বা সরাসরি ফোনে অর্ডারের জন্য কল করুন আমাদের হটলাইনে।',
    type: 'offer',
    imageUrl: '/images/uploaded/img12.jpg',
    altText: 'PureGhor হটলাইন ও কাস্টমার সাপোর্ট ব্যানার',
    targetUrl: '/contact',
    ctaTextBn: 'হটলাইনে যোগাযোগ করুন',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'PURE10',
    discountType: 'percentage',
    value: 10,
    minOrderAmount: 1000,
    maxDiscount: 300,
    usageLimit: 500,
    usedCount: 14,
    expiryDate: '2026-12-31',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'coup-2',
    code: 'WELCOME100',
    discountType: 'fixed',
    value: 100,
    minOrderAmount: 1500,
    usageLimit: 1000,
    usedCount: 42,
    expiryDate: '2026-12-31',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialFAQs: FAQ[] = [
  {
    id: 'faq-1',
    questionBn: 'আপনাদের পণ্যগুলো কি সত্যিই শতভাগ খাঁটি ও কেমিক্যালমুক্ত?',
    answerBn: 'হ্যাঁ, PureGhor-এর প্রতিটি পণ্য সরাসরি নিজস্ব তত্ত্বাবধানে বিশ্বস্ত উৎস ও কৃষকদের থেকে সংগৃহীত। আমরা কোনো প্রকার কৃত্রিম রং, ফ্লেভার বা প্রিজারভেটিভ ব্যবহার করি না এবং নিয়মিত ল্যাব টেস্ট করা হয়।',
    category: 'products',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'faq-2',
    questionBn: 'ডেলিভারি কত দিনের মধ্যে পাওয়া যায় এবং ডেলিভারি চার্জ কত?',
    answerBn: 'সিলেট সদরে ২৪ থেকে ৪৮ ঘণ্টার মধ্যে এবং ঢাকা ও সারা বাংলাদেশে ২ থেকে ৩ কার্যদিবসের মধ্যে হোম ডেলিভারি করা হয়। সিলেট বিভাগে ডেলিভারি চার্জ ৫০ টাকা, ঢাকা সিটিতে ৮০ টাকা এবং ঢাকার বাইরে ১২০-১৩০ টাকা। ২০০০ টাকার বেশি অর্ডারে ফ্রি ডেলিভারি!',
    category: 'delivery',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'faq-3',
    questionBn: 'আমি কি পণ্য হাতে পেয়ে দেখে টাকা পরিশোধ (ক্যাশ অন ডেলিভারি) করতে পারব?',
    answerBn: 'অবশ্যই! আমাদের সারা বাংলাদেশে ক্যাশ অন ডেলিভারি (COD) সুবিধা রয়েছে। ডেলিভারিম্যানের সামনে পার্সেল চেক করে মূল্য পরিশোধ করতে পারবেন।',
    category: 'payment',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'faq-4',
    questionBn: 'পণ্য পছন্দ না হলে বা ক্ষতিগ্রস্ত পেলে রিটার্ন বা রিফান্ড পলিসি কী?',
    answerBn: 'পণ্য পাওয়ার পর যদি কোনো ত্রুটি বা অসন্তোষ থাকে, তবে ডেলিভারির ৪৮ ঘণ্টার মধ্যে আমাদের হেল্পলাইন বা হোয়াটসঅ্যাপে জানালে আমরা দ্রুত ফ্রি রিপ্লেসমেন্ট অথবা সম্পূর্ণ রিফান্ডের ব্যবস্থা করি।',
    category: 'returns',
    displayOrder: 4,
    isActive: true,
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-honey-kalijira',
    productNameBn: 'খাঁটি কালোজিরা ফুলের মধু',
    customerName: 'তানভীর আহমেদ',
    customerPhone: '01819***456',
    rating: 5,
    comment: 'কালোজিরা ফুলের মধু সত্যিই অসাধারণ! চমৎকার সুবাস আর হালকা মিষ্টি স্বাদ। খাঁটি মধুর আসল ফ্লেভার পেয়েছি। প্যাকেজিংও খুব প্রিমিয়াম ছিল।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'rev-2',
    productId: 'prod-nut-combo',
    productNameBn: '৪ জার মেগা বাদাম ও বীজ কম্বো',
    customerName: 'নুসরাত জাহান',
    customerPhone: '01711***982',
    rating: 5,
    comment: '৪টি জারের বাদাম ও কিসমিস একদম তাজা আর মুচমুচে! বাচ্চাদের জন্য প্রতিদিনের নাস্তায় খুব উপকারী। এই দামে এমন কোয়ালিটি সত্যি প্রশংসনীয়।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'rev-3',
    productId: 'prod-balachao',
    productNameBn: 'স্পেশাল হোমমেড ক্রিস্পি চিংড়ি বালাচাও',
    customerName: 'মাহমুদুল হাসান',
    customerPhone: '01912***123',
    rating: 5,
    comment: 'চিংড়ি বালাচাও এর স্বাদ এক কথায় অতুলনীয়! গরম ভাতের সাথে পুরো মুখে লেগে থাকে। কোনো আজেবাজে গন্ধ নেই, দারুণ ক্রিস্পি।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];
