import { StoreSettings, Category, Product, Banner, Coupon, FAQ, Review } from '../types';

export const initialSettings: StoreSettings = {
  storeNameBn: 'পিওর ঘর (PureGhor)',
  storeNameEn: 'PureGhor Organic Store',
  taglineBn: 'সিলেটের বিখ্যাত ব্র্যান্ড — ১০০% খাঁটি ও অর্গানিক পণ্যের বিশ্বস্ত ঠিকানা',
  taglineEn: '100% Pure, Organic & Natural Food Store',
  logoUrl: '/logo.svg',
  faviconUrl: '/favicon.svg',
  phone: '01754-991822',
  whatsapp: '01754-991822',
  email: 'pureghornatural@gmail.com',
  addressBn: 'লালাবাজার, দক্ষিণ সুরমা, সিলেট। আল বুরাক শপিং সিটি, বিশ্বনাথ',
  addressEn: 'Lalabazar, Dakshin Surma, Sylhet. Al Burak Shopping City, Bishwanath',
  businessHours: 'প্রতিদিন সকাল ৯টা থেকে রাত ১০টা পর্যন্ত',
  isCodAvailable: true,
  deliveryCharges: {
    insideDhaka: 80,
    outsideDhaka: 130,
    insideSylhet: 50,
    outsideSylhet: 120,
  },
  freeDeliveryThreshold: 2000,
  socialLinks: {
    facebook: 'https://facebook.com/pureghor',
    instagram: 'https://instagram.com/pureghor',
    youtube: 'https://youtube.com/pureghor',
    whatsapp: 'https://wa.me/8801754991822',
  },
  currency: 'BDT',
  currencySymbol: '৳',
  taxText: 'সকল মূল্যে ভ্যাট অন্তর্ভুক্ত',
  themeColors: {
    primaryGreen: '#5EB809',
    deepGreen: '#004F18',
    warmCream: '#F5FBF2',
    honeyAmber: '#E89D10',
    terracotta: '#B85C38',
    neutralText: '#102B16',
    border: '#DCECD5',
  },
  announcementBar: {
    enabled: true,
    textBn: '🚚 সারা বাংলাদেশে ক্যাশ অন ডেলিভারি | উদ্বোধনী অফারে ২০০০ টাকার অর্ডারে ফ্রি ডেলিভারি!',
    linkUrl: '/shop',
  },
  trustStrip: [
    {
      id: 'ts-1',
      icon: 'ShieldCheck',
      titleBn: 'খাঁটি উৎস থেকে সংগ্রহ',
      descBn: 'সরাসরি কৃষক ও প্রাকৃতিক উৎস থেকে পরীক্ষিত মান',
    },
    {
      id: 'ts-2',
      icon: 'PackageCheck',
      titleBn: 'নিরাপদ ফুড-গ্রেড প্যাকেজিং',
      descBn: 'স্বাস্থ্যসম্মত ও বায়ুরোধী প্রটেক্টিভ জার',
    },
    {
      id: 'ts-3',
      icon: 'Truck',
      titleBn: 'ক্যাশ অন ডেলিভারি',
      descBn: 'পণ্য হাতে পেয়ে চেক করে মূল্য পরিশোধ করুন',
    },
    {
      id: 'ts-4',
      icon: 'Headphones',
      titleBn: 'দ্রুত কাস্টমার সাপোর্ট',
      descBn: 'যেকোনো প্রয়োজনে সরাসরি কল বা হোয়াটসঅ্যাপ করুন',
    },
  ],
  aboutUsContent: {
    headline: 'আমাদের পথচলা ও খাঁটি পণ্যের অঙ্গীকার',
    storyBn: 'PureGhor প্রতিষ্ঠিত হয়েছে ভেজালমুক্ত ও প্রাকৃতিক খাদ্যাভ্যাস গড়ে তোলার ব্রত নিয়ে। আমাদের যাত্রা শুরু সিলেটের পুণ্যভূমি থেকে। মাঠপর্যায় থেকে কোনো প্রকার কেমিক্যাল বা প্রিজারভেটিভ ছাড়া নিখাদ খাবার পৌঁছে দেওয়াই আমাদের প্রধান লক্ষ্য।',
    sourcingBn: 'সুন্দরবনের গভীর অরণ্যের মৌয়ালদের থেকে খাঁটি মধু, যশোরের প্রান্তিক গাছিদের থেকে সংগৃহীত খাঁটি খেজুরের গুড়, সিরাজগঞ্জের দেশি গাভীর দুধ থেকে প্রস্তুতকৃত গাওয়া ঘি এবং নিজস্ব তত্ত্বাবধানে কাঠের ঘানিতে ভাঙানো সরিষার তেল আমরা সংগ্রহ করি।',
    promiseBn: 'আমরা ল্যাব টেস্ট ও কঠোর মান নিয়ন্ত্রণের মাধ্যমে প্রতিটি ব্যাচ পরীক্ষা করি। পণ্যের মান ও আপনার সুস্থতাই আমাদের সর্বোচ্চ অগ্রাধিকার।',
  },
  isSetupComplete: true,
  updatedAt: new Date().toISOString(),
};

export const initialCategories: Category[] = [
  {
    id: 'cat-honey',
    nameBn: 'মধু ও নাটস',
    nameEn: 'Honey & Nuts',
    slug: 'honey-nuts',
    descriptionBn: 'সুন্দরবনের প্রাকৃতিক চাকের মধু, কালোজিরা ফুলের মধু ও প্রিমিয়াম ড্রাই ফ্রুটস।',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    displayOrder: 1,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-ghee-oil',
    nameBn: 'ঘি ও খাঁটি তেল',
    nameEn: 'Ghee & Pure Oils',
    slug: 'ghee-and-oils',
    descriptionBn: 'সিরাজগঞ্জের ঐতিহ্যবাহী গাওয়া ঘি এবং কাঠের ঘানিতে ভাঙানো খাঁটি সরিষার তেল।',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-gur',
    nameBn: 'খেজুরের গুড় ও পাটালি',
    nameEn: 'Date Palm Jaggery',
    slug: 'khejurer-gur',
    descriptionBn: 'যশোরের বিখ্যাত খাঁটি ঝোলা গুড়, নলেন গুড় ও সুস্বাদু পাটালি।',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    displayOrder: 3,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-spices',
    nameBn: 'গুঁড়া মসলা ও বীজ',
    nameEn: 'Pure Spices & Seeds',
    slug: 'spices-and-seeds',
    descriptionBn: 'শতভাগ খাঁটি হলুদের গুঁড়া, লাল মরিচ, ধনিয়া ও প্রিমিয়াম চিয়া সিড।',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    displayOrder: 4,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-tea-coffee',
    nameBn: 'প্রাকৃতিক চা ও পানীয়',
    nameEn: 'Natural Tea & Coffee',
    slug: 'natural-tea-coffee',
    descriptionBn: 'শ্রীমঙ্গল ও সিলেটের বিখ্যাত অর্গানিক গ্রিন টি এবং প্রিমিয়াম অর্থোডক্স ব্ল্যাক টি।',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    displayOrder: 5,
    isActive: true,
    type: 'food',
  },
  {
    id: 'cat-combo',
    nameBn: 'কম্বো ও স্পেশাল অফার',
    nameEn: 'Combo & Special Offers',
    slug: 'combo-offers',
    descriptionBn: 'দৈনন্দিন স্বাস্থ্য সুরক্ষার আকর্ষণীয় সাশ্রয়ী কম্বো প্যাকেজ।',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    displayOrder: 6,
    isActive: true,
    type: 'combo',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    nameBn: 'খাঁটি সুন্দরবনের খলিশা ফুলের মধু',
    nameEn: 'Pure Sundarban Khalisha Honey',
    slug: 'sundarban-khalisha-honey',
    sku: 'PG-HNY-001',
    categoryId: 'cat-honey',
    shortDescriptionBn: 'সুন্দরবনের গহিন অরণ্য থেকে সংগৃহীত কাঁচা ও সম্পূর্ণ প্রক্রিয়াজাতহীন প্রাকৃতিক মধু।',
    descriptionBn: 'খলিশা ফুলের মধু সুন্দরবনের অন্যতম সেরা ও দুর্লভ মধু। এর চমৎকার প্রাকৃতিক সুবাস এবং মৃদু মিষ্টি স্বাদ ছোট বড় সকলের প্রিয়। কোনো প্রকার চিনি মিশ্রণ, হিটিং বা প্রিজারভেটিভ ব্যতীত সরাসরি বোতলজাত করা হয়।',
    price: 950,
    salePrice: 850,
    currency: 'BDT',
    stock: 45,
    lowStockThreshold: 10,
    weight: 500,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 500, salePrice: 450, stock: 30, sku: 'PG-HNY-001-250' },
      { weight: 500, unit: 'gm', price: 950, salePrice: 850, stock: 45, sku: 'PG-HNY-001-500' },
      { weight: 1, unit: 'kg', price: 1800, salePrice: 1650, stock: 20, sku: 'PG-HNY-001-1KG' },
    ],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
        alt: 'খাঁটি সুন্দরবনের খলিশা ফুলের মধু কাচের জারে',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80',
        alt: 'মধু সংগ্রাহক ও প্রাকৃতিক মৌচাক',
      },
    ],
    ingredients: '১০০% প্রাকৃতিক খলিশা ফুলের মধু।',
    nutrition: 'প্রতি ১০০ গ্রামে: ক্যালোরি ৩০৪ kcal, কার্বোহাইড্রেট ৮২.৪ গ্রাম, প্রাকৃতিক ফ্রুক্টোজ ৩৮%, গ্লুকোজ ৩১%।',
    source: 'সুন্দরবন সাতক্ষীরা রেঞ্জ, মৌয়ালদের সহায়তায় সংগৃহীত।',
    storageInstruction: 'স্বাভাবিক তাপমাত্রায় শুষ্ক স্থানে মুখ বন্ধ করে রাখুন। ফ্রিজে রাখবেন না।',
    expiryText: 'উৎপাদনের তারিখ থেকে ২ বছর পর্যন্ত চমৎকার থাকে।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-2', 'prod-6'],
    seoTitle: 'খাঁটি সুন্দরবনের খলিশা ফুলের মধু - PureGhor',
    seoDescription: '১০০% ভেজালমুক্ত সুন্দরবনের খলিশা মধু। ক্যাশ অন ডেলিভারিতে হোম ডেলিভারি নিন।',
    rating: 4.9,
    reviewCount: 28,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    nameBn: 'ঐতিহ্যবাহী গাওয়া ঘি (সিরাজগঞ্জ)',
    nameEn: 'Traditional Cow Ghee (Sirajganj)',
    slug: 'traditional-cow-ghee',
    sku: 'PG-GHEE-001',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'সিরাজগঞ্জের মাঠা থেকে মাখন তুলে জ্বাল দিয়ে তৈরি দানাদার সুগন্ধি গাওয়া ঘি।',
    descriptionBn: 'আমাদের গাওয়া ঘি খাঁটি দেশি গাভীর দুধের মাখন থেকে তৈরি। ঐতিহ্যবাহী পদ্ধতিতে মৃদু আঁচে জ্বাল দেওয়া হয়, যা এনে দেয় চমৎকার সোনালী দানাদার টেক্সচার ও মন মাতানো সুবাস। গরম ভাত, খিচুড়ি কিংবা রান্নায় অনন্য স্বাদ যুক্ত করে।',
    price: 900,
    salePrice: 820,
    currency: 'BDT',
    stock: 35,
    lowStockThreshold: 8,
    weight: 500,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 480, salePrice: 430, stock: 25, sku: 'PG-GHEE-001-250' },
      { weight: 500, unit: 'gm', price: 900, salePrice: 820, stock: 35, sku: 'PG-GHEE-001-500' },
      { weight: 1, unit: 'kg', price: 1750, salePrice: 1600, stock: 15, sku: 'PG-GHEE-001-1KG' },
    ],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1631709497146-a239ef373cf1?auto=format&fit=crop&w=800&q=80',
        alt: 'দানাদার সোনালী গাওয়া ঘি',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% দেশি গাভীর দুধের মাখন।',
    nutrition: 'প্রতি ১০০ গ্রামে: ক্যালোরি ৯০০ kcal, ফ্যাট ৯৯.৫%, ওমেগা-৩ ও ওমেগা-৯ ফ্যাটি এসিড।',
    source: 'সিরাজগঞ্জের বাঘাবাড়ি ও শাহজাদপুর অঞ্চলের গো-খামার।',
    storageInstruction: 'আলো থেকে দূরে স্বাভাবিক তাপমাত্রায় শুকনো চামচ ব্যবহার করে সংরক্ষণ করুন।',
    expiryText: 'প্যাকেজিং এর পর থেকে ৯ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-1', 'prod-3'],
    seoTitle: 'খাঁটি গাওয়া ঘি - দানাদার ও সুগন্ধি | PureGhor',
    seoDescription: 'খাঁটি গাওয়া ঘি সিরাজগঞ্জ থেকে সংগৃহীত। ভেজালহীন সোনালী দানাদার ঘি।',
    rating: 5.0,
    reviewCount: 34,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    nameBn: 'যশোরের স্পেশাল ঝোলা খেজুর গুড়',
    nameEn: 'Jashore Special Date Palm Liquid Gur',
    slug: 'jashore-khejurer-jhola-gur',
    sku: 'PG-GUR-001',
    categoryId: 'cat-gur',
    shortDescriptionBn: 'যশোরের তাজা খেজুরের রস থেকে কোনো কেমিক্যাল ছাড়া জ্বাল দেওয়া নলেন ঝোলা গুড়।',
    descriptionBn: 'খেজুরের গুড়ের রাজধানী যশোর থেকে সরাসরি সংগৃহীত। শীতের ভোরে নামানো মিষ্টি রস দিয়ে ঐতিহ্যবাহী মাটির চুলায় ঘন করে জ্বাল দেওয়া এই ঝোলা গুড়। পিঠা, পায়েস ও রুটির সাথে অতুলনীয়।',
    price: 450,
    salePrice: 390,
    currency: 'BDT',
    stock: 60,
    lowStockThreshold: 12,
    weight: 1,
    unit: 'kg',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        alt: 'যশোরের সুস্বাদু নলেন ঝোলা গুড় মাটির হাঁড়িতে',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% প্রাকৃতিক খেজুরের রস। সোডা ও হাইড্রোস মুক্ত।',
    nutrition: 'আয়রন, ম্যাগনেসিয়াম, পটাশিয়াম ও অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ।',
    source: 'যশোরের খাজুরা ও বাঘারপাড়া অঞ্চল।',
    storageInstruction: 'স্বাভাবিক তাপমাত্রায় অথবা রেফ্রিজারেটরে সংরক্ষণ করুন।',
    expiryText: '৬ মাস পর্যন্ত ভালো থাকে।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-4', 'prod-2'],
    seoTitle: 'যশোরের খাঁটি খেজুরের গুড় - PureGhor',
    seoDescription: 'কেমিক্যালমুক্ত খাঁটি খেজুরের ঝোলা গুড়। পিঠা ও পায়েসের আসল স্বাদ।',
    rating: 4.8,
    reviewCount: 19,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    nameBn: 'কাঠের ঘানিতে ভাঙানো খাঁটি সরিষার তেল',
    nameEn: 'Cold-Pressed Mustard Oil (Wood Churn)',
    slug: 'cold-pressed-mustard-oil',
    sku: 'PG-OIL-001',
    categoryId: 'cat-ghee-oil',
    shortDescriptionBn: 'দেশি মাঘী সরিষা থেকে কাঠের ঘানিতে ধীরগতিতে ভাঙানো প্রথম চাপের ঝাঁঝালো তেল।',
    descriptionBn: 'ধীরগতির কাঠের ঘানিতে ভাঙানোর ফলে তেলের তাপমাত্রা বৃদ্ধি পায় না, যার ফলে সরিষার সমস্ত প্রাকৃতিক পুষ্টিগুণ, ঝাঁঝ ও চমৎকার গন্ধ অটুট থাকে। কোনো প্রকার কেমিক্যাল বা পরিশোধনের স্পর্শ নেই।',
    price: 360,
    salePrice: 320,
    currency: 'BDT',
    stock: 50,
    lowStockThreshold: 15,
    weight: 1,
    unit: 'ltr',
    weightOptions: [
      { weight: 500, unit: 'ml', price: 190, salePrice: 170, stock: 40, sku: 'PG-OIL-001-500' },
      { weight: 1, unit: 'ltr', price: 360, salePrice: 320, stock: 50, sku: 'PG-OIL-001-1L' },
      { weight: 5, unit: 'ltr', price: 1750, salePrice: 1550, stock: 15, sku: 'PG-OIL-001-5L' },
    ],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
        alt: 'কাঠের ঘানির খাঁটি সরিষার তেল কাচের বোতলে',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% দেশি মাঘী সরিষা।',
    nutrition: 'মনোআনস্যাচুরেটেড ফ্যাটি এসিড, ওমেগা-৩ ও ওমেগা-৬ ব্যালেন্স সমৃদ্ধ।',
    source: 'মানিকগঞ্জ ও সিরাজগঞ্জের নিজস্ব তত্ত্বাবধানে পরিচালিত কাঠের ঘানি।',
    storageInstruction: 'সরাসরি রোদ থেকে দূরে ঠান্ডা ও অন্ধকার স্থানে রাখুন।',
    expiryText: 'ভাঙানোর তারিখ থেকে ১২ মাস।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-2', 'prod-5'],
    seoTitle: 'কাঠের ঘানির খাঁটি সরিষার তেল | PureGhor',
    seoDescription: 'প্রাকৃতিক ঝাঁঝালো সরিষার তেল কাঠের ঘানিতে ভাঙানো। স্বাস্থ্যসম্মত রান্নার তেল।',
    rating: 4.9,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    nameBn: 'প্রিমিয়াম অর্গানিক চিয়া সিড (USDA Certified)',
    nameEn: 'Organic Chia Seeds (USDA Certified)',
    slug: 'organic-chia-seeds',
    sku: 'PG-SEED-001',
    categoryId: 'cat-spices',
    shortDescriptionBn: 'উচ্চমানের ডায়েটারি ফাইবার ও ওমেগা-৩ ফ্যাটি এসিড সমৃদ্ধ আমদানিকৃত প্রিমিয়াম চিয়া বীজ।',
    descriptionBn: 'ওজন নিয়ন্ত্রণ, হজম শক্তি বৃদ্ধি এবং হার্ট সুস্থ রাখতে চিয়া সিডের জুড়ি নেই। শতভাগ ধুলাবালিমুক্ত এবং গ্রেড-১ মানের কালো চিয়া সিড। প্রতিদিন সকালে লেবুর পানি, স্মুদি বা ওটসের সাথে খাওয়ার উপযোগী।',
    price: 420,
    salePrice: 360,
    currency: 'BDT',
    stock: 40,
    lowStockThreshold: 10,
    weight: 250,
    unit: 'gm',
    weightOptions: [
      { weight: 250, unit: 'gm', price: 420, salePrice: 360, stock: 40, sku: 'PG-SEED-001-250' },
      { weight: 500, unit: 'gm', price: 780, salePrice: 680, stock: 25, sku: 'PG-SEED-001-500' },
    ],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
        alt: 'প্রিমিয়াম ব্ল্যাক চিয়া সিড জারে',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% অর্গানিক কালো চিয়া বীজ।',
    nutrition: 'প্রতি ১০০ গ্রামে ফাইবার ৩৪ গ্রাম, প্রোটিন ১৬.৫ গ্রাম, ওমেগা-৩ ১৭.৮ গ্রাম।',
    source: 'দক্ষিণ আমেরিকা থেকে সরাসরি আমদানিকৃত এবং ল্যাব-টেস্টেড।',
    storageInstruction: 'শুষ্ক ও ঠান্ডা স্থানে বাতাসমুক্ত বায়ুরোধী জারে রাখুন।',
    expiryText: 'প্যাকেজিং থেকে ১৮ মাস।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: false,
    relatedProductIds: ['prod-1', 'prod-6'],
    seoTitle: 'অর্গানিক চিয়া সিড - PureGhor',
    seoDescription: '১০০% পিওর ব্ল্যাক চিয়া সিড। ওজন নিয়ন্ত্রণ ও ফিটনেসের জন্য সুপারফুড।',
    rating: 4.8,
    reviewCount: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    nameBn: 'শ্রীমঙ্গলের গ্রিন টি ও প্রিমিয়াম অর্থোডক্স চা',
    nameEn: 'Sreemangal Green Tea & Orthodox Tea',
    slug: 'sreemangal-orthodox-green-tea',
    sku: 'PG-TEA-001',
    categoryId: 'cat-tea-coffee',
    shortDescriptionBn: 'শ্রীমঙ্গলের পাহাড়ি বাগানের কোমল দুটি পাতা একটি কুঁড়ি থেকে প্রস্তুতকৃত সুগন্ধি চা।',
    descriptionBn: 'সিলেটের চায়ের রাজধানী শ্রীমঙ্গলের সেরা বাগান থেকে বাছাই করা ফ্রেশ চায়ের পাতা। অ্যান্টিঅক্সিডেন্ট ও ক্যাটেচিন সমৃদ্ধ এই চা ক্লান্তি দূর করে এবং শরীরকে ভেতর থেকে চাঙা রাখে।',
    price: 320,
    salePrice: 280,
    currency: 'BDT',
    stock: 55,
    lowStockThreshold: 10,
    weight: 200,
    unit: 'gm',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
        alt: 'শ্রীমঙ্গলের সবুজ ফ্রেশ গ্রিন টি',
        isPrimary: true,
      },
    ],
    ingredients: '১০০% প্রাকৃতিক পুরো পাতার গ্রিন টি।',
    nutrition: 'সমৃদ্ধ পলিফেনল, ক্যাটেচিন ও জিরো ক্যালোরি রিফ্রেশমেন্ট।',
    source: 'শ্রীমঙ্গল চা বাগান, মৌলভীবাজার, সিলেট।',
    storageInstruction: 'বাতাস ও আর্দ্রতামুক্ত জারে সংরক্ষণ করুন।',
    expiryText: 'উৎপাদনের তারিখ থেকে ২৪ মাস।',
    isPublished: true,
    isFeatured: false,
    isSpecialOffer: false,
    relatedProductIds: ['prod-1', 'prod-5'],
    seoTitle: 'শ্রীমঙ্গলের খাঁটি গ্রিন টি | PureGhor',
    seoDescription: 'সিলেটের শ্রীমঙ্গলের ফ্রেশ গ্রিন টি। শরীর সতেজ ও সুস্থ রাখার প্রাকৃতিক পানীয়।',
    rating: 4.7,
    reviewCount: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    nameBn: 'স্বাস্থ্য সুরক্ষা কম্বো প্যাক (মধু + ঘি + সরিষার তেল)',
    nameEn: 'Health Protection Combo Pack',
    slug: 'health-protection-combo-pack',
    sku: 'PG-CMB-001',
    categoryId: 'cat-combo',
    shortDescriptionBn: 'খলিশা মধু (৫০০ গ্রাম) + খাঁটি গাওয়া ঘি (৫০০ গ্রাম) + কাঠের ঘানির সরিষার তেল (১ লিটার)।',
    descriptionBn: 'আপনার পরিবারের প্রতিদিনের স্বাস্থ্য সুরক্ষায় তিনটি অপরিহার্য খাঁটি অর্গানিক খাদ্যের মেগা কম্বো প্যাক। আলাদা কেনার চেয়ে এই প্যাকে পাচ্ছেন আকর্ষণীয় অতিরিক্ত ছাড় ও ফ্রি ডেলিভারি!',
    price: 2210,
    salePrice: 1890,
    currency: 'BDT',
    stock: 25,
    lowStockThreshold: 5,
    weight: 2,
    unit: 'kg',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
        alt: 'স্বাস্থ্য সুরক্ষা স্পেশাল কম্বো প্যাক',
        isPrimary: true,
      },
    ],
    ingredients: 'খলিশা মধু ৫০০ গ্রাম + গাওয়া ঘি ৫০০ গ্রাম + সরিষার তেল ১ লিটার।',
    nutrition: 'সম্পূর্ণ প্রাকৃতিক প্রোটিন, এসেনশিয়াল ফ্যাটি এসিড এবং ইমিউনিটি বুস্টার সমৃদ্ধ।',
    source: 'সুন্দরবন, সিরাজগঞ্জ ও মানিকগঞ্জের সরাসরি সোর্সিং।',
    storageInstruction: 'উপাদান অনুযায়ী শুকনো ও স্বাভাবিক তাপমাত্রায় সংরক্ষণ করুন।',
    expiryText: 'স্ব স্ব পণ্যের গায়ে উল্লেখিত মেয়াদ প্রযোজ্য।',
    isPublished: true,
    isFeatured: true,
    isSpecialOffer: true,
    offerExpiryDate: '2026-12-31',
    relatedProductIds: ['prod-1', 'prod-2', 'prod-4'],
    seoTitle: 'মেগা সেভিংস অর্গানিক কম্বো অফার | PureGhor',
    seoDescription: 'মধু, ঘি ও সরিষার তেলের আকর্ষণীয় কম্বো প্যাক। ফ্রি ডেলিভারিতে অর্ডার করুন।',
    rating: 5.0,
    reviewCount: 56,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-hero-1',
    titleBn: 'আপনার পরিবারের জন্য সত্যিকারের খাঁটি খাবার',
    subtitleBn: 'নির্বাচিত উৎস থেকে সংগ্রহ, যত্নে প্যাকেজিং এবং ঘরে পৌঁছে দেওয়া।',
    type: 'hero',
    imageUrl: '', // Dynamic or uses generated clean organic banner
    altText: 'PureGhor খাঁটি ও ভেজালমুক্ত অর্গানিক পণ্য পরিবার',
    targetUrl: '/shop',
    ctaTextBn: 'এখনই শপ করুন',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ban-offer-1',
    titleBn: 'সিলেটের বিখ্যাত ব্র্যান্ড PureGhor এখন বিশ্বনাথ',
    subtitleBn: 'উদ্বোধন উপলক্ষে থাকছে ১০% বিশেষ ডিসকাউন্ট! কোড: PURE10',
    type: 'offer',
    imageUrl: '',
    altText: 'উদ্বোধনী অফার ব্যানার ১০% ডিসকাউন্ট',
    targetUrl: '/shop',
    ctaTextBn: 'অফার দেখুন',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'PURE10',
    discountType: 'percentage',
    value: 10,
    minOrderAmount: 1000,
    maxDiscount: 300,
    usageLimit: 500,
    usedCount: 14,
    expiryDate: '2026-12-31',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'coup-2',
    code: 'WELCOME100',
    discountType: 'fixed',
    value: 100,
    minOrderAmount: 1500,
    usageLimit: 1000,
    usedCount: 42,
    expiryDate: '2026-12-31',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialFAQs: FAQ[] = [
  {
    id: 'faq-1',
    questionBn: 'আপনাদের পণ্যগুলো কি সত্যিই শতভাগ খাঁটি ও কেমিক্যালমুক্ত?',
    answerBn: 'হ্যাঁ, PureGhor-এর প্রতিটি পণ্য সরাসরি নিজস্ব তত্ত্বাবধানে বিশ্বস্ত উৎস ও কৃষকদের থেকে সংগৃহীত। আমরা কোনো প্রকার কৃত্রিম রং, ফ্লেভার বা প্রিজারভেটিভ ব্যবহার করি না এবং নিয়মিত ল্যাব টেস্ট করা হয়।',
    category: 'products',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'faq-2',
    questionBn: 'ডেলিভারি কত দিনের মধ্যে পাওয়া যায় এবং ডেলিভারি চার্জ কত?',
    answerBn: 'সিলেট সদরে ২৪ থেকে ৪৮ ঘণ্টার মধ্যে এবং ঢাকা ও সারা বাংলাদেশে ২ থেকে ৩ কার্যদিবসের মধ্যে হোম ডেলিভারি করা হয়। সিলেট বিভাগে ডেলিভারি চার্জ ৫০ টাকা, ঢাকা সিটিতে ৮০ টাকা এবং ঢাকার বাইরে ১২০-১৩০ টাকা। ২০০০ টাকার বেশি অর্ডারে ফ্রি ডেলিভারি!',
    category: 'delivery',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'faq-3',
    questionBn: 'আমি কি পণ্য হাতে পেয়ে দেখে টাকা পরিশোধ (ক্যাশ অন ডেলিভারি) করতে পারব?',
    answerBn: 'অবশ্যই! আমাদের সারা বাংলাদেশে ক্যাশ অন ডেলিভারি (COD) সুবিধা রয়েছে। ডেলিভারিম্যানের সামনে পার্সেল চেক করে মূল্য পরিশোধ করতে পারবেন।',
    category: 'payment',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'faq-4',
    questionBn: 'পণ্য পছন্দ না হলে বা ক্ষতিগ্রস্ত পেলে রিটার্ন বা রিফান্ড পলিসি কী?',
    answerBn: 'পণ্য পাওয়ার পর যদি কোনো ত্রুটি বা অসন্তোষ থাকে, তবে ডেলিভারির ৪৮ ঘণ্টার মধ্যে আমাদের হেল্পলাইন বা হোয়াটসঅ্যাপে জানালে আমরা দ্রুত ফ্রি রিপ্লেসমেন্ট অথবা সম্পূর্ণ রিফান্ডের ব্যবস্থা করি।',
    category: 'returns',
    displayOrder: 4,
    isActive: true,
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productNameBn: 'খাঁটি সুন্দরবনের খলিশা ফুলের মধু',
    customerName: 'তানভীর আহমেদ',
    customerPhone: '01819***456',
    rating: 5,
    comment: 'সুন্দরবনের খলিশা মধু সত্যিই অসাধারণ! চমৎকার সুবাস আর হালকা মিষ্টি স্বাদ। খাঁটি মধুর আসল ফ্লেভার পেয়েছি। প্যাকেজিংও খুব প্রিমিয়াম ছিল।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'rev-2',
    productId: 'prod-2',
    productNameBn: 'ঐতিহ্যবাহী গাওয়া ঘি (সিরাজগঞ্জ)',
    customerName: 'নুসরাত জাহান',
    customerPhone: '01711***982',
    rating: 5,
    comment: 'ঘি এর ঘ্রাণেই মন ভরে যায়। দানাদার সোনালী ঘি। গরম ভাতে একটু নিলে পুরো ঘরের বাতাসে সুবাস ছড়িয়ে পড়ে। PureGhor-কে ধন্যবাদ খাঁটি জিনিস দেওয়ার জন্য।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    productNameBn: 'যশোরের স্পেশাল ঝোলা খেজুর গুড়',
    customerName: 'মাহমুদুল হাসান',
    customerPhone: '01912***123',
    rating: 5,
    comment: 'শীতের পিঠা বানানোর জন্য নিয়েছিলাম। কোনো কেমিক্যালের গন্ধ নেই, একদম খাঁটি মিষ্টি খেজুরের রসের আসল টেস্ট। বারবার অর্ডার করব ইনশাআল্লাহ।',
    isVerifiedBuyer: true,
    status: 'approved',
    isFeatured: true,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];
